using CounterStrikeSharp.API.Core;

namespace jRandomSkills.src.player;

public interface ISkill
{
    public static void LoadSkill() { }
    public static void EnableSkill(CCSPlayerController player) { }
    public static void DisableSkill(CCSPlayerController player) { }
    public static void UseSkill(CCSPlayerController player) { }
    public static void TypeSkill(CCSPlayerController player, string[] commands) { }
}

public enum Skills
{
    Aimbot,
    Anomaly,
    AntyFlash,
    AntyHead,
    Armored,
    Assassin,
    Astronaut,
    Behind,
    Catapult,
    Chicken,
    Commando,
    Cutter,
    Darkness,
    Deactivator,
    Deaf,
    Disarmament,
    Dopamine,
    Dracula,
    Duplicator,
    Dwarf,
    EnemySpawn,
    Evade,
    ExplosiveShot,
    FalconEye,
    FireBullets,
    Flash,
    Fortnite,
    Fov,
    FriendlyFire,
    FrozenDecoy,
    Ghost,
    Glaz,
    Glitch,
    Glue,
    GodMode,
    Thorns,
    ReZombie,
    HealingSmoke,
    HolyHandGrenade,
    Impostor,
    InfiniteAmmo,
    Jackal,
    Jammer,
    JumpBan,
    JumpingJack,
    KillerFlash,
    LongZeus,
    Medic,
    Muhammed,
    Noclip,
    NoMoney,
    NoNades,
    None,
    OneShot,
    PawelJumper,
    Phoenix,
    Pilot,
    Planter,
    Prosthesis,
    PsychicDefusing,
    QuickShot,
    RadarHack,
    Rambo,
    RandomWeapon,
    RefillOnKill,
    Regeneration,
    Replicator,
    Retreat,
    ReturnToSender,
    TimeManipulator,
    RichBoy,
    Rubber,
    Saper,
    ScriptKid,
    SecondLife,
    Shade,
    ShortBomb,
    Silent,
    Soldier,
    SoundMaker,
    Spectator,
    SwapPosition,
    TeleKiller,
    RandomGuns,
    Thief,
    ThirdEye,
    ToxicSmoke,
    Wallhack,
    WeaponsSwap,
    Zeus,
}
